from actions.base_action import BaseAction
from pages.BloodIssuePage import BloodIssuePage
import time
from selenium.webdriver.common.keys import Keys

class BloodIssueAction(BaseAction):

    def clickBloodBankMenu(self):
        self.click(BloodIssuePage.blood_bank_menu)

    def clickBloodIssueDetails(self):
        self.click(BloodIssuePage.blood_issue_details)

    def clickIssueBloodButton(self):
        self.click(BloodIssuePage.issue_blood_button)

    def selectPatient(self, patient_name):
        self.click(BloodIssuePage.patient_dropdown)

        self.send_keys(
            BloodIssuePage.search_box,
            str(patient_name)
        )

        self.wait_for_visibility(
            BloodIssuePage.dynamic_option(str(patient_name))
        )

        self.click(
            BloodIssuePage.dynamic_option(str(patient_name))
        )

    def enterIssueDate(self, issue_date):
        element = self.wait_for_visibility(
            BloodIssuePage.issue_date
        )

        element.clear()
        element.send_keys(issue_date)

    def selectDoctor(self, doctor):
        self.click(BloodIssuePage.doctor_dropdown)

        self.send_keys(
            BloodIssuePage.search_box,
            doctor
        )

        self.wait_for_visibility(
            BloodIssuePage.dynamic_option(doctor)
        )

        self.click(
            BloodIssuePage.dynamic_option(doctor)
        )

    def isBloodGroupAutoGenerated(self):
        blood_group = self.get_text(
            BloodIssuePage.blood_group
        )

        return blood_group.strip() != ""

    def selectBloodBag(self):
        self.click(BloodIssuePage.blood_bag_dropdown)

        self.wait_for_visibility(
            BloodIssuePage.first_option
        )

        self.click(
            BloodIssuePage.first_option
        )

    def selectChargeCategory(self, charge_category):
        self.click(
            BloodIssuePage.charge_category_dropdown
        )

        self.send_keys(
            BloodIssuePage.search_box,
            charge_category
        )

        self.wait_for_visibility(
            BloodIssuePage.dynamic_option(charge_category)
        )

        self.click(
            BloodIssuePage.dynamic_option(charge_category)
        )

    def selectChargeName(self, charge_name):

        self.click(BloodIssuePage.charge_name_dropdown)

        search = self.wait_for_visibility(
        BloodIssuePage.search_box
    )

        search.clear()
        search.send_keys(charge_name)

    # Trigger keyboard event without changing text
        search.send_keys(Keys.SHIFT)

        self.wait_for_visibility(
        BloodIssuePage.dynamic_option(charge_name)
    )

        self.click(
        BloodIssuePage.dynamic_option(charge_name)
    )

    def isPaymentAmountAutoGenerated(self):
        amount = self.wait_for_visibility(
            BloodIssuePage.payment_amount
        ).get_attribute("value")

        return amount.strip() != ""

    def clickSaveButton(self):
        self.click(BloodIssuePage.save_button)

    def isIssuedBloodRecordDisplayed(self):
        message = self.get_text(
            BloodIssuePage.success_message
        )

        return "success" in message.lower()
    def clickDeleteButton(self):

        self.hover(
            BloodIssuePage.first_row
        )

        self.wait_for_clickable(
            BloodIssuePage.delete_button
        ).click()

    def acceptDeleteAlert(self):

        self.handle_alert()

    def isRecordDeletedSuccessfully(self):

        return self.is_displayed(
            BloodIssuePage.delete_message
        )
    def getValidationMessage(self):
        return self.get_text(BloodIssuePage.validation_message)
    def clickNewPatientButton(self):
        self.click(BloodIssuePage.new_patient)


    def isAddPatientPopupDisplayed(self):
        return self.is_displayed(
        BloodIssuePage.add_patient_popup
    )


    def enterPatientDetails(
    self,
    name,
    year,
    month,
    day
):

        self.send_keys(
        BloodIssuePage.name,
        name
    )

        self.send_keys(
        BloodIssuePage.age_year,
        year
    )

        self.send_keys(
        BloodIssuePage.age_month,
        month
    )

        self.send_keys(
        BloodIssuePage.age_day,
        day
    )


    def clickPatientSaveButton(self):
        self.click(
        BloodIssuePage.patient_save
    )


    def isPatientAddedSuccessfully(self):

        message = self.get_text(
        BloodIssuePage.success_message
    )

        return (
        "record saved successfully"
        in message.lower()
    )
    def clickNewPatientButton(self):
        self.click(BloodIssuePage.new_patient)

    def isAddPatientPopupDisplayed(self):
        return self.is_displayed(
        BloodIssuePage.add_patient_popup
    )

    def enterPatientDetails(
    self,
    name,
    year,
    month,
    day
):

        self.send_keys(
        BloodIssuePage.name,
        name
    )

        self.send_keys(
        BloodIssuePage.age_year,
        year
    )

        self.send_keys(
        BloodIssuePage.age_month,
        month
    )

        self.send_keys(
        BloodIssuePage.age_day,
        day
    )

    def clickPatientSaveButton(self):
        self.click(BloodIssuePage.patient_save)

    def isPatientAddedSuccessfully(self):

        message = self.get_text(
        BloodIssuePage.success_message
    )

        return (
        "record saved successfully"
        in message.lower()
    )
        