import pytest
from actions.LoginAction import LoginAction
from actions.BloodIssueAction import BloodIssueAction
from utilities.excel_reader import get_data
from utilities.csv_reader import get_data as csv_data

class TestBloodIssueManagement:

    @pytest.mark.parametrize("patient_name,doctor,issue_date,charge_category,charge_name", get_data("BloodIssue.xlsx", "ValidDetails"))
    def test_issue_blood_with_valid_details(self, setup, patient_name, doctor, issue_date, charge_category, charge_name):
        login = LoginAction(setup)
        login.validLogin()
        blood = BloodIssueAction(setup)
        blood.clickBloodBankMenu()
        blood.clickBloodIssueDetails()
        blood.clickIssueBloodButton()
        blood.selectPatient(patient_name)
        blood.enterIssueDate(issue_date)
        blood.selectDoctor(doctor)
        assert blood.isBloodGroupAutoGenerated()
        blood.selectBloodBag()
        blood.selectChargeCategory(charge_category)
        blood.selectChargeName(charge_name)
        assert blood.isPaymentAmountAutoGenerated()
        blood.clickSaveButton()
        assert blood.isIssuedBloodRecordDisplayed()

    def test_delete_issued_blood_record(self, setup):
        login = LoginAction(setup)
        login.validLogin()
        blood = BloodIssueAction(setup)
        blood.clickBloodBankMenu()
        blood.clickBloodIssueDetails()
        blood.clickDeleteButton()
        blood.acceptDeleteAlert()
        assert blood.isRecordDeletedSuccessfully()

    def test_issue_blood_empty_mandatory_fields(self, setup):
        login = LoginAction(setup)
        login.validLogin()
        blood = BloodIssueAction(setup)
        blood.clickBloodBankMenu()
        blood.clickBloodIssueDetails()
        blood.clickIssueBloodButton()
        blood.clickSaveButton()
        validation_message = blood.getValidationMessage()
        assert "Issue Date field is required" in validation_message

    @pytest.mark.parametrize("name,year,month,day", csv_data("AddPatient.csv"))
    def test_add_new_patient(self, setup, name, year, month, day):
        login = LoginAction(setup)
        login.validLogin()
        blood = BloodIssueAction(setup)
        blood.clickBloodBankMenu()
        blood.clickBloodIssueDetails()
        blood.clickIssueBloodButton()
        blood.clickNewPatientButton()
        assert blood.isAddPatientPopupDisplayed()
        blood.enterPatientDetails(name, year, month, day)
        blood.clickPatientSaveButton()
        assert blood.isPatientAddedSuccessfully()